### PR TITLE
Added 2 new functions in FFT.hs 

### PR DESCRIPTION
**Pull request by Haskell-mouse**
I have added 2 functions: "fft1D_r'" and "fft1D_3r'". This functions make 1D FFT  on all rows in 2D (first) and 3D (second) arrays. 
It was very useful for my task =)

Maybe it's worthwhile to come up with a more beautiful name.

### CODE REVIEW

**Comment by tmcdonell** [comment]
Oh, this is great! Thanks!
I am travelling at the moment but will take a look as soon as I can (:

**Comment by Haskell-mouse** [comment]
In fact it is easy to implement such operation on array of any dimension for PTX backend and i cant implement it for Native ,  because of function "go" with the type 
`go :: FFTWReal r => CArray (Int,Int) (Complex r) -> CArray (Int,Int) (Complex r)`

it contains a tuple with the number of elements in which is equal to the dimension. 
I tried to do something with it, but i still dont undestend clearly haskell`s type-level machinery. 
(I still learn it and it is my first language).

> I am travelling at the moment but will take a look as soon as I can (:

Happy Travel !

**Comment by Haskell-mouse** [comment]
Is everything ok?  
I ask because this functions are needed by [wigner-ville-accelerate ](https://hackage.haskell.org/package/wigner-ville-accelerate-0.1.0.2)

**Comment by tmcdonell** [comment]
Hi! Sorry, I have been swamped since coming back, I'll try to have a look today. So sorry for the delays ):

**Comment by Haskell-mouse** [comment]
Oh... Sorry for disturbing ( 
I just thought that maybe something wrong with code.

**Pull request merged**
